# Generated by Django 4.1.7 on 2023-03-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'cars', 'verbose_name_plural': 'cars'},
        ),
    ]
