# Generated by Django 4.1.7 on 2023-03-07 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_cars_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Goods_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
