# Generated by Django 4.1.7 on 2023-03-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_options'),
        ('car', '0006_cars_goods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car', to='user.users'),
        ),
    ]
