# Generated by Django 4.1.7 on 2023-03-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'goods', 'verbose_name_plural': 'goods'},
        ),
    ]
