# Generated by Django 4.1.7 on 2023-03-06 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'orders', 'verbose_name_plural': 'orders'},
        ),
        migrations.AddField(
            model_name='orders',
            name='Goods_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
